[theme]
primaryColor = "#CCA43B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#363636"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
